# Generated by Django 4.0.5 on 2022-06-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=3)),
                ('a', models.IntegerField()),
                ('b', models.IntegerField()),
                ('result', models.FloatField(null=True)),
            ],
        ),
    ]
